//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UraxBpcPno34Api.ResourceFiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UraxBpcPno34Api.ResourceFiles.Message", typeof(Message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount is required.
        /// </summary>
        internal static string AmountRequired {
            get {
                return ResourceManager.GetString("AmountRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application area is required.
        /// </summary>
        internal static string ApplicationAreaRequired {
            get {
                return ResourceManager.GetString("ApplicationAreaRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application is required.
        /// </summary>
        internal static string ApplicationRequired {
            get {
                return ResourceManager.GetString("ApplicationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counrty code is required.
        /// </summary>
        internal static string CountryCodeRequired {
            get {
                return ResourceManager.GetString("CountryCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency code is required.
        /// </summary>
        internal static string CurrencyCodeRequired {
            get {
                return ResourceManager.GetString("CurrencyCodeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data area is required.
        /// </summary>
        internal static string DataAreaRequired {
            get {
                return ResourceManager.GetString("DataAreaRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data type is required.
        /// </summary>
        internal static string DatatypeRequired {
            get {
                return ResourceManager.GetString("DatatypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviornment is required.
        /// </summary>
        internal static string EnvironmentRequired {
            get {
                return ResourceManager.GetString("EnvironmentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gcc tax partner group is required.
        /// </summary>
        internal static string GccTaxPartnerGroupRequired {
            get {
                return ResourceManager.GetString("GccTaxPartnerGroupRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locale is required.
        /// </summary>
        internal static string LocaleRequired {
            get {
                return ResourceManager.GetString("LocaleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model year is required.
        /// </summary>
        internal static string ModelYearRequired {
            get {
                return ResourceManager.GetString("ModelYearRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required.
        /// </summary>
        internal static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter is required.
        /// </summary>
        internal static string ParametersRequired {
            get {
                return ResourceManager.GetString("ParametersRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pno34  is required.
        /// </summary>
        internal static string Pno34Required {
            get {
                return ResourceManager.GetString("Pno34Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pno list is required.
        /// </summary>
        internal static string PnoListRequired {
            get {
                return ResourceManager.GetString("PnoListRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pno is required.
        /// </summary>
        internal static string PnoRequired {
            get {
                return ResourceManager.GetString("PnoRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Date is required.
        /// </summary>
        internal static string PriceDateRequired {
            get {
                return ResourceManager.GetString("PriceDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price is required.
        /// </summary>
        internal static string PriceRequired {
            get {
                return ResourceManager.GetString("PriceRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Type is required.
        /// </summary>
        internal static string PriceTypeRequired {
            get {
                return ResourceManager.GetString("PriceTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested datetime created  is required.
        /// </summary>
        internal static string RequestDatetimeCreatedRequired {
            get {
                return ResourceManager.GetString("RequestDatetimeCreatedRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respnose created datetime is required.
        /// </summary>
        internal static string ResponseCreatedDateTimeRequired {
            get {
                return ResourceManager.GetString("ResponseCreatedDateTimeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revision is required.
        /// </summary>
        internal static string RevisionRequired {
            get {
                return ResourceManager.GetString("RevisionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sender is required.
        /// </summary>
        internal static string SenderRequired {
            get {
                return ResourceManager.GetString("SenderRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence id is required.
        /// </summary>
        internal static string SequenceIdRequired {
            get {
                return ResourceManager.GetString("SequenceIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status is required.
        /// </summary>
        internal static string StatusRequired {
            get {
                return ResourceManager.GetString("StatusRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Structure Week is required.
        /// </summary>
        internal static string StructureWeekRequired {
            get {
                return ResourceManager.GetString("StructureWeekRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax is required.
        /// </summary>
        internal static string TaxRequired {
            get {
                return ResourceManager.GetString("TaxRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is required.
        /// </summary>
        internal static string ValueRequired {
            get {
                return ResourceManager.GetString("ValueRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vat position is required.
        /// </summary>
        internal static string VatPositionRequired {
            get {
                return ResourceManager.GetString("VatPositionRequired", resourceCulture);
            }
        }
    }
}
