INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(2,'BG','Bulgarian (Bulgaria)','bg-BG','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(3,'ES','Catalan (Catalan)','ca-ES','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(4,'TW','Chinese (Taiwan)','zh-TW','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(5,'CZ','Czech (Czech Republic)','cs-CZ','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(6,'DK','Danish (Denmark)','da-DK','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(7,'DE','German (Germany)','de-DE','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(8,'GR','Greek (Greece)','el-GR','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(9,'US','English (United States)','en-US','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(10,'FI','Finnish (Finland)','fi-FI','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(11,'FR','French (France)','fr-FR','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(12,'IL','Hebrew (Israel)','he-IL','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(13,'HU','Hungarian (Hungary)','hu-HU','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(14,'IS','Icelandic (Iceland)','is-IS','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(15,'IT','Italian (Italy)','it-IT','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(16,'JP','Japanese (Japan)','ja-JP','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(17,'KR','Korean (Korea)','ko-KR','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(18,'NL','Dutch (Netherlands)','nl-NL','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(19,'NO','Norwegian, Bokmål (Norway)','nb-NO','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(20,'PL','Polish (Poland)','pl-PL','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(21,'BR','Portuguese (Brazil)','pt-BR','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(22,'RO','Romanian (Romania)','ro-RO','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(23,'RU','Russian (Russia)','ru-RU','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(24,'HR','Croatian (Croatia)','hr-HR','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(25,'SK','Slovak (Slovakia)','sk-SK','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(26,'AL','Albanian (Albania)','sq-AL','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(27,'SE','Swedish (Sweden)','sv-SE','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(28,'TH','Thai (Thailand)','th-TH','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(29,'TR','Turkish (Turkey)','tr-TR','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(30,'PK','Urdu (Islamic Republic of Pakistan)','ur-PK','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(31,'ID','Indonesian (Indonesia)','id-ID','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(32,'UA','Ukrainian (Ukraine)','uk-UA','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(33,'BY','Belarusian (Belarus)','be-BY','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(34,'SI','Slovenian (Slovenia)','sl-SI','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(35,'EE','Estonian (Estonia)','et-EE','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(36,'LV','Latvian (Latvia)','lv-LV','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(37,'LT','Lithuanian (Lithuania)','lt-LT','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(38,'IR','Persian (Iran)','fa-IR','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(39,'VN','Vietnamese (Vietnam)','vi-VN','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(40,'AM','Armenian (Armenia)','hy-AM','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(41,'AZ','Azeri (Latin, Azerbaijan)','az-Latn-AZ','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(42,'ES','Basque (Basque)','eu-ES','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(43,'MK','Macedonian (Former Yugoslav Republic of Macedonia)','mk-MK','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(44,'ZA','Afrikaans (South Africa)','af-ZA','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(45,'GE','Georgian (Georgia)','ka-GE','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(46,'FO','Faroese (Faroe Islands)','fo-FO','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(47,'IN','Hindi (India)','hi-IN','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(48,'MY','Malay (Malaysia)','ms-MY','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(49,'KZ','Kazakh (Kazakhstan)','kk-KZ','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(50,'KG','Kyrgyz (Kyrgyzstan)','ky-KG','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(51,'KE','Kiswahili (Kenya)','sw-KE','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(52,'UZ','Uzbek (Latin, Uzbekistan)','uz-Latn-UZ','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(53,'RU','Tatar (Russia)','tt-RU','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(54,'IN','Punjabi (India)','pa-IN','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(55,'IN','Gujarati (India)','gu-IN','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(56,'IN','Tamil (India)','ta-IN','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(57,'IN','Telugu (India)','te-IN','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(58,'IN','Kannada (India)','kn-IN','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(59,'IN','Marathi (India)','mr-IN','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(60,'IN','Sanskrit (India)','sa-IN','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(61,'MN','Mongolian (Cyrillic, Mongolia)','mn-MN','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(62,'ES','Galician (Galician)','gl-ES','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(63,'IN','Konkani (India)','kok-IN','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(64,'SY','Syriac (Syria)','syr-SY','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(65,'MV','Divehi (Maldives)','dv-MV','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(66,'IQ','Arabic (Iraq)','ar-IQ','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(67,'CN','Chinese (Peoples Republic of China)','zh-CN','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(68,'CH','German (Switzerland)','de-CH','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(69,'GB','English (United Kingdom)','en-GB','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(70,'MX','Spanish (Mexico)','es-MX','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(71,'BE','French (Belgium)','fr-BE','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(72,'CH','Italian (Switzerland)','it-CH','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(73,'BE','Dutch (Belgium)','nl-BE','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(74,'NO','Norwegian, Nynorsk (Norway)','nn-NO','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(75,'PT','Portuguese (Portugal)','pt-PT','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(76,'CS','Serbian (Latin, Serbia)','sr-Latn-CS','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(77,'FI','Swedish (Finland)','sv-FI','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(78,'AZ','Azeri (Cyrillic, Azerbaijan)','az-Cyrl-AZ','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(79,'BN','Malay (Brunei Darussalam)','ms-BN','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(80,'UZ','Uzbek (Cyrillic, Uzbekistan)','uz-Cyrl-UZ','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(81,'EG','Arabic (Egypt)','ar-EG','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(82,'HK','Chinese (Hong Kong S.A.R.)','zh-HK','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(83,'AT','German (Austria)','de-AT','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(84,'AU','English (Australia)','en-AU','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(85,'ES','Spanish (Spain)','es-ES','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(86,'CA','French (Canada)','fr-CA','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(87,'CS','Serbian (Cyrillic, Serbia)','sr-Cyrl-CS','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(88,'LY','Arabic (Libya)','ar-LY','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(89,'SG','Chinese (Singapore)','zh-SG','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(90,'LU','German (Luxembourg)','de-LU','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(91,'CA','English (Canada)','en-CA','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(92,'GT','Spanish (Guatemala)','es-GT','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(93,'CH','French (Switzerland)','fr-CH','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(94,'DZ','Arabic (Algeria)','ar-DZ','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(95,'MO','Chinese (Macao S.A.R.)','zh-MO','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(96,'LI','German (Liechtenstein)','de-LI','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(97,'NZ','English (New Zealand)','en-NZ','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(98,'CR','Spanish (Costa Rica)','es-CR','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(99,'LU','French (Luxembourg)','fr-LU','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(100,'MA','Arabic (Morocco)','ar-MA','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(101,'IE','English (Ireland)','en-IE','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(102,'PA','Spanish (Panama)','es-PA','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(103,'MC','French (Principality of Monaco)','fr-MC','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(104,'TN','Arabic (Tunisia)','ar-TN','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(105,'ZA','English (South Africa)','en-ZA','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(106,'DO','Spanish (Dominican Republic)','es-DO','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(107,'OM','Arabic (Oman)','ar-OM','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(108,'JM','English (Jamaica)','en-JM','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(109,'VE','Spanish (Venezuela)','es-VE','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(110,'YE','Arabic (Yemen)','ar-YE','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(111,'O29','English (Caribbean)','en-029','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(112,'CO','Spanish (Colombia)','es-CO','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(113,'SY','Arabic (Syria)','ar-SY','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(114,'BZ','English (Belize)','en-BZ','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(115,'PE','Spanish (Peru)','es-PE','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(116,'JO','Arabic (Jordan)','ar-JO','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(117,'TT','English (Trinidad and Tobago)','en-TT','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(118,'AR','Spanish (Argentina)','es-AR','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(119,'LB','Arabic (Lebanon)','ar-LB','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(120,'ZW','English (Zimbabwe)','en-ZW','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(121,'EC','Spanish (Ecuador)','es-EC','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(122,'KW','Arabic (Kuwait)','ar-KW','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(123,'PH','English (Republic of the Philippines)','en-PH','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(124,'CL','Spanish (Chile)','es-CL','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(125,'AE','Arabic (U.A.E.)','ar-AE','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(126,'UY','Spanish (Uruguay)','es-UY','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(127,'BH','Arabic (Bahrain)','ar-BH','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(128,'PY','Spanish (Paraguay)','es-PY','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(129,'QA','Arabic (Qatar)','ar-QA','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(130,'BO','Spanish (Bolivia)','es-BO','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(131,'SV','Spanish (El Salvador)','es-SV','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(132,'HN','Spanish (Honduras)','es-HN','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(133,'NI','Spanish (Nicaragua)','es-NI','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(134,'PR','Spanish (Puerto Rico)','es-PR','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(135,'NO','Sami, Southern (Norway)','sma-NO','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(136,'BA','Serbian (Cyrillic, Bosnia and Herzegovina)','sr-Cyrl-BA','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(137,'ZA','Zulu','zu-ZA','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(138,'ZA','Xhosa','xh-ZA','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(139,'NL','Frisian (Netherlands)','fy-NL','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(140,'ZA','Setswana (South Africa)','tn-ZA','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(141,'SE','Sami, Northern (Sweden)','se-SE','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(142,'SE','Sami, Southern (Sweden)','sma-SE','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(143,'PH','Filipino (Philippines)','fil-PH','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(144,'FI','Sami, Inari (Finland)','smn-FI','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(145,'PE','Quechua (Peru)','quz-PE','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(146,'FI','Sami, Northern (Finland)','se-FI','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(147,'FI','Sami, Skolt (Finland)','sms-FI','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(148,'GB','Welsh','cy-GB','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(149,'BA','Croatian (Bosnia and Herzegovina)','hr-BA','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(150,'CA','Inuktitut (Latin, Canada)','iu-Latn-CA','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(151,'BA','Bosnian (Cyrillic, Bosnia and Herzegovina)','bs-Cyrl-BA','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(152,'CA','Mohawk (Mohawk)','moh-CA','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(153,'NO','Sami, Lule (Norway)','smj-NO','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(154,'CL','Mapudungun (Chile)','arn-CL','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(155,'NZ','Maori','mi-NZ','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(156,'EC','Quechua (Ecuador)','quz-EC','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(157,'IE','Irish (Ireland)','ga-IE','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(158,'CH','Romansh (Switzerland)','rm-CH','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(159,'BA','Serbian (Latin, Bosnia and Herzegovina)','sr-Latn-BA','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(160,'SE','Sami, Lule (Sweden)','smj-SE','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(161,'LU','Luxembourgish (Luxembourg)','lb-LU','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(162,'ZA','Sesotho sa Leboa (South Africa)','ns-ZA','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(163,'BO','Quechua (Bolivia)','quz-BO','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(164,'NO','Sami, Northern (Norway)','se-NO','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(165,'MT','Maltese','mt-MT','ADMIN','ADMIN')
INSERT INTO dbo.Languages( LanguageId, CountryCode,[Language], LanguageCountrycode,CreatedBy,UpdatedBy) VALUES(166,'BA','Bosnian (Latin, Bosnia and Herzegovina)','bs-Latn-BA','ADMIN','ADMIN')

