//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UraxUIServiceWebApi.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ISO3166
    {
        public string Territory { get; set; }
        public string Parent { get; set; }
        public string Local_code { get; set; }
        public string Full_code { get; set; }
        public string Parent_code { get; set; }
        public string Code_Standard { get; set; }
    }
}
