//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UraxUIServiceWebApi.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class LanguageDetail
    {
        public int LanguageDetailsId { get; set; }
        public long TaxMasterId { get; set; }
        public int LanguageId { get; set; }
        public string TaxName { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public bool IsDefault { get; set; }
    
        public virtual Language Language { get; set; }
        public virtual TaxMaster TaxMaster { get; set; }
    }
}
