//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UraxUIServiceWebApi.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Market
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Market()
        {
            this.PartnerCodeMappers = new HashSet<PartnerCodeMapper>();
            this.TaxMasters = new HashSet<TaxMaster>();
        }
    
        public long MarketId { get; set; }
        public int CountryCodeId { get; set; }
        public string TaxPartnerGroup { get; set; }
        public int currencyId { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public string SubdivisionCode { get; set; }
        public string TaxTerritory { get; set; }
        public bool FeatureLevelTax { get; set; }
    
        public virtual CountryCode CountryCode { get; set; }
        public virtual CurrencyDetail CurrencyDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartnerCodeMapper> PartnerCodeMappers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaxMaster> TaxMasters { get; set; }
    }
}
