//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UraxUIServiceWebApi.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pno12FixedParameters
    {
        public int Pno12Id { get; set; }
        public int Pno12PdId { get; set; }
        public string ParameterValue { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual Pno12 Pno12 { get; set; }
        public virtual Pno12 Pno121 { get; set; }
        public virtual Pno12 Pno122 { get; set; }
        public virtual Pno12ParameterDefinition Pno12ParameterDefinition { get; set; }
        public virtual Pno12ParameterDefinition Pno12ParameterDefinition1 { get; set; }
        public virtual Pno12ParameterDefinition Pno12ParameterDefinition2 { get; set; }
    }
}
