//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UraxUIServiceWebApi.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PnoParameter
    {
        public long PnoParameterId { get; set; }
        public long PnoId { get; set; }
        public int VariableMasterId { get; set; }
        public string Value { get; set; }
        public bool Isactive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
    
        public virtual PnoNumber PnoNumber { get; set; }
        public virtual PnoVariableMaster PnoVariableMaster { get; set; }
    }
}
