//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UraxUIServiceWebApi.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class URAXEntities : DbContext
    {
        public URAXEntities()
            : base("name=URAXEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CountryCode> CountryCodes { get; set; }
        public virtual DbSet<CurrencyDetail> CurrencyDetails { get; set; }
        public virtual DbSet<Formula> Formulae { get; set; }
        public virtual DbSet<FormulaDefinitionDependencyDetail> FormulaDefinitionDependencyDetails { get; set; }
        public virtual DbSet<ISO3166> ISO3166 { get; set; }
        public virtual DbSet<LanguageDetail> LanguageDetails { get; set; }
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<LookUpDetail> LookUpDetails { get; set; }
        public virtual DbSet<LookUpGroup> LookUpGroups { get; set; }
        public virtual DbSet<LookupGroupDetail> LookupGroupDetails { get; set; }
        public virtual DbSet<Market> Markets { get; set; }
        public virtual DbSet<MaterialNew> MaterialNews { get; set; }
        public virtual DbSet<ParameterDetail> ParameterDetails { get; set; }
        public virtual DbSet<ParameterGroupMaster> ParameterGroupMasters { get; set; }
        public virtual DbSet<Pno12> Pno12 { get; set; }
        public virtual DbSet<Pno12FixedParameters> Pno12FixedParameters { get; set; }
        public virtual DbSet<Pno12ParameterDefinition> Pno12ParameterDefinition { get; set; }
        public virtual DbSet<Pno12ParameterType> Pno12ParameterType { get; set; }
        public virtual DbSet<Pno12UnitOfMeasurement> Pno12UnitOfMeasurement { get; set; }
        public virtual DbSet<PnoGroupMaster> PnoGroupMasters { get; set; }
        public virtual DbSet<PnoNumber> PnoNumbers { get; set; }
        public virtual DbSet<PnoParameter> PnoParameters { get; set; }
        public virtual DbSet<PnoVariableMaster> PnoVariableMasters { get; set; }
        public virtual DbSet<SubdivisionCode> SubdivisionCodes { get; set; }
        public virtual DbSet<Tax> Taxes { get; set; }
        public virtual DbSet<TaxMaster> TaxMasters { get; set; }
        public virtual DbSet<TaxVersion> TaxVersions { get; set; }
        public virtual DbSet<UserDetail> UserDetails { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<Variable> Variables { get; set; }
    }
}
