//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UraxUIServiceWebApi.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Variable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Variable()
        {
            this.Formulae = new HashSet<Formula>();
            this.FormulaDefinitionDependencyDetails = new HashSet<FormulaDefinitionDependencyDetail>();
            this.LookupGroupDetails = new HashSet<LookupGroupDetail>();
        }
    
        public long VariableId { get; set; }
        public long TaxId { get; set; }
        public string VariableName { get; set; }
        public Nullable<decimal> Value { get; set; }
        public Nullable<int> UnitTypeId { get; set; }
        public int VariableTypeId { get; set; }
        public Nullable<bool> IslookUp { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public string TestValue { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Formula> Formulae { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormulaDefinitionDependencyDetail> FormulaDefinitionDependencyDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LookupGroupDetail> LookupGroupDetails { get; set; }
        public virtual Tax Tax { get; set; }
    }
}
