//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UraxUIServiceWebApi.ResourceFiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UraxUIServiceWebApi.ResourceFiles.Message", typeof(Message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization is required..
        /// </summary>
        internal static string AuthorizationReq {
            get {
                return ResourceManager.GetString("AuthorizationReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is already exist with same CDSID..
        /// </summary>
        internal static string CDSIDDuplicatemsg {
            get {
                return ResourceManager.GetString("CDSIDDuplicatemsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CDSID is required..
        /// </summary>
        internal static string CDSIDReq {
            get {
                return ResourceManager.GetString("CDSIDReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data is not present..
        /// </summary>
        internal static string CmnDataNotFound {
            get {
                return ResourceManager.GetString("CmnDataNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error :.
        /// </summary>
        internal static string CmnError {
            get {
                return ResourceManager.GetString("CmnError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Heading is required..
        /// </summary>
        internal static string ContentHeadingReq {
            get {
                return ResourceManager.GetString("ContentHeadingReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Text is required..
        /// </summary>
        internal static string ContextTextReq {
            get {
                return ResourceManager.GetString("ContextTextReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CopyTax already exists..
        /// </summary>
        internal static string CopyTaxDuplicatemsg {
            get {
                return ResourceManager.GetString("CopyTaxDuplicatemsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country already exists with the same Country Code..
        /// </summary>
        internal static string CountryCodeDuplicatemsg {
            get {
                return ResourceManager.GetString("CountryCodeDuplicatemsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country already exists with the same Country Code Id..
        /// </summary>
        internal static string CountryCodeIdDuplicatemsg {
            get {
                return ResourceManager.GetString("CountryCodeIdDuplicatemsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Code Id is required..
        /// </summary>
        internal static string CountryCodeIdReq {
            get {
                return ResourceManager.GetString("CountryCodeIdReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Code is required..
        /// </summary>
        internal static string CountryCodeReq {
            get {
                return ResourceManager.GetString("CountryCodeReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country  already exists with the same Country Name..
        /// </summary>
        internal static string CountryNameDuplicatemsg {
            get {
                return ResourceManager.GetString("CountryNameDuplicatemsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Name is required..
        /// </summary>
        internal static string CountryNameReq {
            get {
                return ResourceManager.GetString("CountryNameReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By is required..
        /// </summary>
        internal static string CreatedByReq {
            get {
                return ResourceManager.GetString("CreatedByReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created On is required..
        /// </summary>
        internal static string CreatedOnReq {
            get {
                return ResourceManager.GetString("CreatedOnReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency is already exist with same Currency Code..
        /// </summary>
        internal static string CurrencyCodeDuplicatemsg {
            get {
                return ResourceManager.GetString("CurrencyCodeDuplicatemsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency code is required..
        /// </summary>
        internal static string CurrencyCodeReq {
            get {
                return ResourceManager.GetString("CurrencyCodeReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency details already exist with the same Currency Name..
        /// </summary>
        internal static string CurrencyDetalisDuplicatemsg {
            get {
                return ResourceManager.GetString("CurrencyDetalisDuplicatemsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Id is required..
        /// </summary>
        internal static string CurrencyIdReq {
            get {
                return ResourceManager.GetString("CurrencyIdReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate row details not allowed.
        /// </summary>
        internal static string DuplicateRowDatamsg {
            get {
                return ResourceManager.GetString("DuplicateRowDatamsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TaxName provided is already taken for this country..
        /// </summary>
        internal static string DuplicateTaxNamemsg {
            get {
                return ResourceManager.GetString("DuplicateTaxNamemsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable Ids contain duplicate entries..
        /// </summary>
        internal static string DupVarIdmsg {
            get {
                return ResourceManager.GetString("DupVarIdmsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date is required..
        /// </summary>
        internal static string EndDateReq {
            get {
                return ResourceManager.GetString("EndDateReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FeatureLevelTax is required.
        /// </summary>
        internal static string FeatureLevelTaxReq {
            get {
                return ResourceManager.GetString("FeatureLevelTaxReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name is required..
        /// </summary>
        internal static string FirstNameReq {
            get {
                return ResourceManager.GetString("FirstNameReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   cannot select range type as &apos;Range&apos;..
        /// </summary>
        internal static string FixedRangeTypemsg {
            get {
                return ResourceManager.GetString("FixedRangeTypemsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable name is already used in.
        /// </summary>
        internal static string formsg {
            get {
                return ResourceManager.GetString("formsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formula expression is wrong..
        /// </summary>
        internal static string FormulaExpressionWrong {
            get {
                return ResourceManager.GetString("FormulaExpressionWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one language can be set to default &apos;Yes&apos;..
        /// </summary>
        internal static string illegalDefaultmsg {
            get {
                return ResourceManager.GetString("illegalDefaultmsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date should not be less than current date..
        /// </summary>
        internal static string InvalidEndDatemsg {
            get {
                return ResourceManager.GetString("InvalidEndDatemsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date should not be less than start date..
        /// </summary>
        internal static string InvalidEndStartCombmsg {
            get {
                return ResourceManager.GetString("InvalidEndStartCombmsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GroupDetails Id provided is invalid..
        /// </summary>
        internal static string InvalidGroupDetailsIdmsg {
            get {
                return ResourceManager.GetString("InvalidGroupDetailsIdmsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Id provided does not exist..
        /// </summary>
        internal static string InvalidImgIdmsg {
            get {
                return ResourceManager.GetString("InvalidImgIdmsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided Language Id is invalid..
        /// </summary>
        internal static string InvalidLangIdmsg {
            get {
                return ResourceManager.GetString("InvalidLangIdmsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LookupGroup Id is invalid..
        /// </summary>
        internal static string InvalidlgIdmsg {
            get {
                return ResourceManager.GetString("InvalidlgIdmsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid LookUp Group Id is Provided..
        /// </summary>
        internal static string InvalidLookupGroupIdmsg {
            get {
                return ResourceManager.GetString("InvalidLookupGroupIdmsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lookup Id provided is invalid..
        /// </summary>
        internal static string InvalidLookUpIdmsg {
            get {
                return ResourceManager.GetString("InvalidLookUpIdmsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid market Id is provided..
        /// </summary>
        internal static string InvalidMarketIdmsg {
            get {
                return ResourceManager.GetString("InvalidMarketIdmsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid country code is  provided..
        /// </summary>
        internal static string InvalidMarNameMsg {
            get {
                return ResourceManager.GetString("InvalidMarNameMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum value and maximum value is not valid..
        /// </summary>
        internal static string InvalidMinMaxMsg {
            get {
                return ResourceManager.GetString("InvalidMinMaxMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MNId provided is invalid..
        /// </summary>
        internal static string InvalidMNIdmsg {
            get {
                return ResourceManager.GetString("InvalidMNIdmsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid RangeType Id provided.It should be 12 or 13..
        /// </summary>
        internal static string InvalidRangeTypemsg {
            get {
                return ResourceManager.GetString("InvalidRangeTypemsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record already exists with greater than this start date..
        /// </summary>
        internal static string InvalidStartDatemsg {
            get {
                return ResourceManager.GetString("InvalidStartDatemsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Price Base value is invalid..
        /// </summary>
        internal static string InvalidTaxFlowIdmsg {
            get {
                return ResourceManager.GetString("InvalidTaxFlowIdmsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Id provided is invalid..
        /// </summary>
        internal static string InvalidTaxIdmsg {
            get {
                return ResourceManager.GetString("InvalidTaxIdmsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided taxmaster Id is invalid..
        /// </summary>
        internal static string InvalidTaxMasterIdmsg {
            get {
                return ResourceManager.GetString("InvalidTaxMasterIdmsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax name cannot be a variable name..
        /// </summary>
        internal static string InvalidTaxNamemsg {
            get {
                return ResourceManager.GetString("InvalidTaxNamemsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid tax position Id is provided..
        /// </summary>
        internal static string InvalidTaxPositionmsg {
            get {
                return ResourceManager.GetString("InvalidTaxPositionmsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid tax version Id provided..
        /// </summary>
        internal static string InvalidTaxVersionIdmsg {
            get {
                return ResourceManager.GetString("InvalidTaxVersionIdmsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable Id is invalid..
        /// </summary>
        internal static string InvalidVarIdmsg {
            get {
                return ResourceManager.GetString("InvalidVarIdmsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   cannot be used as variable name..
        /// </summary>
        internal static string InvalidVarmsg {
            get {
                return ResourceManager.GetString("InvalidVarmsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  are invalid variable names..
        /// </summary>
        internal static string Invarmsg {
            get {
                return ResourceManager.GetString("Invarmsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsActive is required..
        /// </summary>
        internal static string IsActiveReq {
            get {
                return ResourceManager.GetString("IsActiveReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsLookUp is required..
        /// </summary>
        internal static string IsLookUpReq {
            get {
                return ResourceManager.GetString("IsLookUpReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language  already exists for this tax..
        /// </summary>
        internal static string LanguageDuplicatemsg {
            get {
                return ResourceManager.GetString("LanguageDuplicatemsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Id is required..
        /// </summary>
        internal static string LanguageIdReq {
            get {
                return ResourceManager.GetString("LanguageIdReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language name is required..
        /// </summary>
        internal static string LanguageNameReq {
            get {
                return ResourceManager.GetString("LanguageNameReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged in date is required..
        /// </summary>
        internal static string LoggedInDateReq {
            get {
                return ResourceManager.GetString("LoggedInDateReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lookupdetails already exist..
        /// </summary>
        internal static string LookUpDetailDuplicatemsg {
            get {
                return ResourceManager.GetString("LookUpDetailDuplicatemsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable name already  exists..
        /// </summary>
        internal static string LookUpGroupDetailDuplicatemsg {
            get {
                return ResourceManager.GetString("LookUpGroupDetailDuplicatemsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LookupGroup already exist..
        /// </summary>
        internal static string LookUpGroupDuplicatemsg {
            get {
                return ResourceManager.GetString("LookUpGroupDuplicatemsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LookUpGroup Id is required..
        /// </summary>
        internal static string LookUpGroupIdReq {
            get {
                return ResourceManager.GetString("LookUpGroupIdReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LookUp Group Name already exists for this tax type..
        /// </summary>
        internal static string LookupGroupNameDuplicatemsg {
            get {
                return ResourceManager.GetString("LookupGroupNameDuplicatemsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LookUpGroup  name is required..
        /// </summary>
        internal static string LookUpGroupNameReq {
            get {
                return ResourceManager.GetString("LookUpGroupNameReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LookUpGroup is required..
        /// </summary>
        internal static string LookUpGroupReq {
            get {
                return ResourceManager.GetString("LookUpGroupReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same Tax territory already exists for the selected Country..
        /// </summary>
        internal static string MarketDuplicatemsg {
            get {
                return ResourceManager.GetString("MarketDuplicatemsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation Order is already taken..
        /// </summary>
        internal static string MarketIdPriorityCombDuplicatemsg {
            get {
                return ResourceManager.GetString("MarketIdPriorityCombDuplicatemsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market Id is required..
        /// </summary>
        internal static string MarketIdReq {
            get {
                return ResourceManager.GetString("MarketIdReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market already exists  with the same market name..
        /// </summary>
        internal static string MarketNameDuplicatemsg {
            get {
                return ResourceManager.GetString("MarketNameDuplicatemsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Market name is required..
        /// </summary>
        internal static string MarketNameReq {
            get {
                return ResourceManager.GetString("MarketNameReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Territory is already exist..
        /// </summary>
        internal static string MarketTaxTerritoryDuplicatemsg {
            get {
                return ResourceManager.GetString("MarketTaxTerritoryDuplicatemsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOOKUP,OUTPUT,INPUT,FIXED,CALCULATED.
        /// </summary>
        internal static string MasterVariableList {
            get {
                return ResourceManager.GetString("MasterVariableList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reserved words cannot be used as variable name..
        /// </summary>
        internal static string MasterVariablemsg {
            get {
                return ResourceManager.GetString("MasterVariablemsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaterialNews already exists..
        /// </summary>
        internal static string MaterialNewsDuplicatemsg {
            get {
                return ResourceManager.GetString("MaterialNewsDuplicatemsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max length is 200.
        /// </summary>
        internal static string MaxLength200 {
            get {
                return ResourceManager.GetString("MaxLength200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max length is 50.
        /// </summary>
        internal static string MaxLength50 {
            get {
                return ResourceManager.GetString("MaxLength50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum value should be lesser than maximum value..
        /// </summary>
        internal static string MinMaxMsg {
            get {
                return ResourceManager.GetString("MinMaxMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No image exists with this MNId..
        /// </summary>
        internal static string NullImgmsg {
            get {
                return ResourceManager.GetString("NullImgmsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Official email Id is required..
        /// </summary>
        internal static string OfficialEmailReq {
            get {
                return ResourceManager.GetString("OfficialEmailReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIN,ROUNDDOWN,ROUNDUP,EXP,IF,MAX,ROUND,NOT,+,-,/,*,&lt;&gt;,&lt;=,&gt;=,&gt;,&lt;,^,%,&quot;,(,),=,..
        /// </summary>
        internal static string OperatorsList {
            get {
                return ResourceManager.GetString("OperatorsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter Group Id is required..
        /// </summary>
        internal static string ParameterGroupIdReq {
            get {
                return ResourceManager.GetString("ParameterGroupIdReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number is required..
        /// </summary>
        internal static string PhoneNoReq {
            get {
                return ResourceManager.GetString("PhoneNoReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority Value already exists..
        /// </summary>
        internal static string PriorityDuplicatemsg {
            get {
                return ResourceManager.GetString("PriorityDuplicatemsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority Value is required..
        /// </summary>
        internal static string PriorityReq {
            get {
                return ResourceManager.GetString("PriorityReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish start date should not be a past date..
        /// </summary>
        internal static string PublishDatemsg {
            get {
                return ResourceManager.GetString("PublishDatemsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published tax formula cannot be modified..
        /// </summary>
        internal static string Publishedformulamsg {
            get {
                return ResourceManager.GetString("Publishedformulamsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published lookup details cannot be modified..
        /// </summary>
        internal static string PublishedLookupmsg {
            get {
                return ResourceManager.GetString("PublishedLookupmsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published tax variables cannot be modified..
        /// </summary>
        internal static string PublishedVarmsg {
            get {
                return ResourceManager.GetString("PublishedVarmsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Price Base shall not be added to a tax version already Published.
        /// </summary>
        internal static string PublishedVermsg {
            get {
                return ResourceManager.GetString("PublishedVermsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range type is mismatched.Please delete lookupdata first before changes rangeType..
        /// </summary>
        internal static string RangeTypLookUpgroupeMisMatchmsg {
            get {
                return ResourceManager.GetString("RangeTypLookUpgroupeMisMatchmsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input variables name cannot be given for a User-defined variable name..
        /// </summary>
        internal static string RestrictedInputmsg {
            get {
                return ResourceManager.GetString("RestrictedInputmsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxes cannot be published which are no longer valid (Expired)..
        /// </summary>
        internal static string RestrictedTaxVersionStatusIdmsg {
            get {
                return ResourceManager.GetString("RestrictedTaxVersionStatusIdmsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is an Invalid variable name..
        /// </summary>
        internal static string SingleInvarmsg {
            get {
                return ResourceManager.GetString("SingleInvarmsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date is required..
        /// </summary>
        internal static string StartDateReq {
            get {
                return ResourceManager.GetString("StartDateReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status ID is required..
        /// </summary>
        internal static string StatusIDReq {
            get {
                return ResourceManager.GetString("StatusIDReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum and Minimum GCC tax partner group name lengths are 0, 20..
        /// </summary>
        internal static string SubmarketCodeLength {
            get {
                return ResourceManager.GetString("SubmarketCodeLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submarket code  is required..
        /// </summary>
        internal static string SubMarketCodeReq {
            get {
                return ResourceManager.GetString("SubMarketCodeReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Price Base already exists for the given Tax Version period..
        /// </summary>
        internal static string TaxFlowIdDuplicatemsg {
            get {
                return ResourceManager.GetString("TaxFlowIdDuplicatemsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Flow Id is required..
        /// </summary>
        internal static string TaxFlowIdReq {
            get {
                return ResourceManager.GetString("TaxFlowIdReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Id is required..
        /// </summary>
        internal static string TaxIdReq {
            get {
                return ResourceManager.GetString("TaxIdReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable details already exist for the given Tax.
        /// </summary>
        internal static string TaxIdVarNameComboDuplicatemsg {
            get {
                return ResourceManager.GetString("TaxIdVarNameComboDuplicatemsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TaxIdVarNameComboDuplicatemsg2 {
            get {
                return ResourceManager.GetString("TaxIdVarNameComboDuplicatemsg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TaxMaster is already exist for the given TaxMasterId..
        /// </summary>
        internal static string TaxMasterDuplicatemsg {
            get {
                return ResourceManager.GetString("TaxMasterDuplicatemsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TaxMaster Id is required..
        /// </summary>
        internal static string TaxMasterIdReq {
            get {
                return ResourceManager.GetString("TaxMasterIdReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Name is required..
        /// </summary>
        internal static string TaxNameReq {
            get {
                return ResourceManager.GetString("TaxNameReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TaxTerritory already exists..
        /// </summary>
        internal static string TaxTerritoryDuplicate {
            get {
                return ResourceManager.GetString("TaxTerritoryDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TaxTerritory is required..
        /// </summary>
        internal static string TaxTerritoryReq {
            get {
                return ResourceManager.GetString("TaxTerritoryReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Version Id is required..
        /// </summary>
        internal static string TaxVersionIdReq {
            get {
                return ResourceManager.GetString("TaxVersionIdReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Type Id is required..
        /// </summary>
        internal static string UnitTypeIdReq {
            get {
                return ResourceManager.GetString("UnitTypeIdReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated By is required..
        /// </summary>
        internal static string UpdatedByReq {
            get {
                return ResourceManager.GetString("UpdatedByReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated On is required..
        /// </summary>
        internal static string UpdatedOnReq {
            get {
                return ResourceManager.GetString("UpdatedOnReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Role Id is required..
        /// </summary>
        internal static string UserRoleIdReq {
            get {
                return ResourceManager.GetString("UserRoleIdReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Type Id is required..
        /// </summary>
        internal static string UserTypeIdReq {
            get {
                return ResourceManager.GetString("UserTypeIdReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is required..
        /// </summary>
        internal static string ValueReq {
            get {
                return ResourceManager.GetString("ValueReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable value cant be null for fixed type..
        /// </summary>
        internal static string ValueRequired {
            get {
                return ResourceManager.GetString("ValueRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable Details already exist..
        /// </summary>
        internal static string VariableDuplicatemsg {
            get {
                return ResourceManager.GetString("VariableDuplicatemsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   already exists..
        /// </summary>
        internal static string VariableIdDuplication {
            get {
                return ResourceManager.GetString("VariableIdDuplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    cannot be used in this formula..
        /// </summary>
        internal static string VariableIdmsg {
            get {
                return ResourceManager.GetString("VariableIdmsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable Id is required..
        /// </summary>
        internal static string VariableIdReq {
            get {
                return ResourceManager.GetString("VariableIdReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable name cannot be an Operator name..
        /// </summary>
        internal static string VariableNameFunmsg {
            get {
                return ResourceManager.GetString("VariableNameFunmsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable Name is required..
        /// </summary>
        internal static string VariableNameReq {
            get {
                return ResourceManager.GetString("VariableNameReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable Type Id is required..
        /// </summary>
        internal static string VariableTypeIdReq {
            get {
                return ResourceManager.GetString("VariableTypeIdReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable Value is required..
        /// </summary>
        internal static string VariableValueReq {
            get {
                return ResourceManager.GetString("VariableValueReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected Version period already exists..
        /// </summary>
        internal static string VersionConflictmsg {
            get {
                return ResourceManager.GetString("VersionConflictmsg", resourceCulture);
            }
        }
    }
}
